import { TRowData } from "types/types";

export const rows: TRowData[] = [
  {
    id: 1,
    fullName: "Snow",
    email: "jon@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    message: "mon message",
  },
  {
    id: 2,
    fullName: "Lannister",
    email: "cersei@gmail.com",
    contact: "0707965744",
    interne: "Interne en médecine",
    message:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore consequatur ea expedita, non, dolores enim odit similique autem dignissimos quaerat odio eum iure sit quas eligendi amet ratione ullam mollitia omnis cupiditate esse ipsa! Blanditiis rerum dolor modi tempora. Maiores, reprehenderit? Et quidem adipisci magnam dignissimos nobis minus fugiat hic libero consequuntur impedit quae dolorem omnis facere nihil expedita, dolor labore quod atque molestias ad culpa! Nesciunt amet suscipit modi dignissimos magnam sit alias repudiandae eum nostrum voluptas ipsa consectetur molestias repellat ab harum officia officiis quidem numquam adipisci aut illum pariatur dolores, similique est! Porro natus distinctio quos corrupti, fugiat omnis illo assumenda dignissimos. Nemo voluptate debitis, nulla cum ea corrupti earum quibusdam autem officia dignissimos. Nulla, maxime praesentium.",
  },
  {
    id: 3,
    fullName: "Lannister",
    email: "jaime@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    message: "mon message",
  },
  {
    id: 4,
    fullName: "Stark",
    email: "arya@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    message: "mon message",
  },
  {
    id: 5,
    fullName: "Targaryen",
    email: "daenerys@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    message: "mon message",
  },
  {
    id: 6,
    fullName: "Melisandre",
    email: "null@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    message: "mon message",
  },
  {
    id: 7,
    fullName: "Clifford",
    email: "ferrara@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    message: "mon message",
  },
  {
    id: 8,
    fullName: "Frances",
    email: "rossini@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    message: "mon message",
  },
  {
    id: 9,
    fullName: "Roxie",
    email: "harvey@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    message: "mon message",
  },
];

export const rowsArticle = [
  {
    id: 1,
    fullName: "Snow",
    email: "jon@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
  {
    id: 2,
    fullName: "Lannister",
    email: "cersei@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
  {
    id: 3,
    fullName: "Lannister",
    email: "jaime@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
  {
    id: 4,
    fullName: "Stark",
    email: "arya@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
  {
    id: 5,
    fullName: "Targaryen",
    email: "daenerys@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
  {
    id: 6,
    fullName: "Melisandre",
    email: "null@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
  {
    id: 7,
    fullName: "Clifford",
    email: "ferrara@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
  {
    id: 8,
    fullName: "Frances",
    email: "rossini@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
  {
    id: 9,
    fullName: "Roxie",
    email: "harvey@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
    fichier: "telecharger-mon-fichier",
  },
];


export const rowsTraining = [
  {
    id: 1,
    fullName: "Snow",
    date: "22/06/2024",
    email: "jon@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
  },
  {
    id: 2,
    fullName: "Lannister",
    date: "22/06/2024",
    email: "cersei@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
  },
  {
    id: 3,
    fullName: "Lannister",
    date: "22/06/2024",
    email: "jaime@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
  },
  {
    id: 4,
    fullName: "Stark",
    date: "22/06/2024",
    email: "arya@gmail.com",
    contact: "0707965744",
    interne: "Interne en pharmacie",
  },
];
